require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Petman' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'PetmanTests' do
    inherit! :complete
    #
    # Pods for testing
  
  end


end
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  


target 'Petman-tvOS' do
  # Pods for Petman-tvOS

  target 'Petman-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end


# post_install do |installer|
#   find_and_replace("../node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m",
#   "_currentFrame.CGImage;","_currentFrame.CGImage ;} else { [super displayLayer:layer];")
# end

# def find_and_replace(dir, findstr, replacestr)
# Dir[dir].each do |name|
#     text = File.read(name)
#     replace = text.gsub(findstr,replacestr)
#     if text != replace
#         puts "Fix: " + name
#         File.open(name, "w") { |file| file.puts replace }
#         STDOUT.flush
#     end
# end
# Dir[dir + '*/'].each(&method(:find_and_replace))
# end